[package]
name = "mzfmt"
version = "0.1.1"
edition = "2021"
description = "SQL pretty printer for the Materialize dialect"
repository = "https://github.com/mjibson/mzfmt"
license-file = "LICENSE.txt"

[dependencies]
clap = { version = "2" }
pretty = "0.11.3"
mz-sql-parser = { path = "materialize/src/sql-parser", default-features = false }
structopt = { version = "0.3", default-features = false }

[dev-dependencies]
datadriven = "0.6"
