[package]
name = "mzfmt"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "2" }
pretty = "0.11.3"
mz-sql-parser = { path = "../../materialize/src/sql-parser", default-features = false }
structopt = { version = "0.3", default-features = false }

[dev-dependencies]
datadriven = "0.6"
