[package]
name = "mzfmt"
version = "0.2.0"
edition = "2021"
description = "SQL pretty printer for the Materialize dialect"
repository = "https://github.com/mjibson/mzfmt"
license-file = "LICENSE.txt"

[dependencies]
clap = { version = "2" }
mz-sql-pretty = { git = "https://github.com/MaterializeInc/materialize.git", rev = "bccfacbaaab97ccfb6d3d3fee4185742f981027d", default-features = false }
structopt = { version = "0.3", default-features = false }

[dev-dependencies]
datadriven = "0.6"
