[package]
name = "mzfmt"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "2" }
pretty = "0.10"
sql-parser = { git = "https://github.com/MaterializeInc/materialize.git", rev = "9411720984aa64cd385d5b034fcab41dc6f4acd5" }
structopt = { version = "0.3", default-features = false }

[dev-dependencies]
datadriven = "0.6"
sql = { git = "https://github.com/MaterializeInc/materialize.git", rev = "9411720984aa64cd385d5b034fcab41dc6f4acd5" }
