[package]
name = "mzfmt"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
#sql-parser = { git = "https://github.com/MaterializeInc/materialize.git", tag = "v0.9.3" }
sql-parser = { path = "../../materialize/src/sql-parser" }
pretty = "0.10"
wasm-bindgen = "0.2"

# ../../.cargo/bin/wasm-pack build --target web
