[package]
name = "web"
version = "0.1.0"
authors = ["Matt Jibson <matt.jibson@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
mzfmt = { path = ".." }
wasm-bindgen = "0.2.83"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
