[package]
name = "web"
version = "0.0.0"
authors = ["Matt Jibson <matt.jibson@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mz-sql-pretty = { git = "https://github.com/MaterializeInc/materialize.git", rev = "bccfacbaaab97ccfb6d3d3fee4185742f981027d", default-features = false }
wasm-bindgen = "0.2.88"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
